apiVersion: v1
kind: Service
metadata:
  name: kubernetes-hello-world-vYAML-service
spec:
  type: NodePort
  selector:
    app: kubernetes-hello-world-vYAML
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 8080